spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Cần chuyển DDL-AUTO sang 'validate' hoặc 'none' cho môi trường production/CI/CD
spring.jpa.hibernate.ddl-auto=create-drop


# spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASSWORD}

# # MySQL thường dùng MySQL5Dialect hoặc MySQL8Dialect
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# # Tùy môi trường
# spring.jpa.hibernate.ddl-auto=update
